### ISSUE TITLE
feature request: Permit to choose http for development

### ISSUE THREAD

**Issue by lakano** [ungoldman/nano-s3#3]
Hi !
Thanks for your package, could you please add an option to permit to choose 'http' rather than 'https' in your target value?
The goal is to use it for the development stack with minio.
Regards,

**Comment by ungoldman** [comment]
✅ Resolved in 1692d57
🚀 Released in `nano-s3@1.1.0`

`nano-s3` now has a `protocol` option which defaults to `https` but can be set to `http`.

See updated docs for more info!
